"""Add agent and credential models

Revision ID: 823191907d58
Revises: 
Create Date: 2026-03-06 13:29:47.856921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823191907d58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('parent_agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.Enum('ORCHESTRATOR', 'AUTONOMOUS', 'ASSISTANT', 'TOOL', name='agent_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.Enum('ROOT', 'DELEGATED', 'EPHEMERAL', name='trust_level_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='agent_status_enum'), nullable=False),
    sa.Column('max_child_depth', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deactivated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], name=op.f('fk_agents_parent_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_parent_agent_id'), 'agents', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_trust_level'), 'agents', ['trust_level'], unique=False)
    op.create_table('credentials',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('API_KEY', 'CLIENT_SECRET', 'MTLS_CERT', 'BOOTSTRAP', name='credential_type_enum'), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_rotated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_credentials_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials'))
    )
    op.create_index(op.f('ix_credentials_agent_id'), 'credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_prefix'), 'credentials', ['prefix'], unique=False)
    op.create_index(op.f('ix_credentials_type'), 'credentials', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_prefix'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_agent_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_agents_trust_level'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_parent_agent_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
