"""add_signing_key_table

Revision ID: bede3c340be9
Revises: 03a6519ac6a1
Create Date: 2026-03-06 18:02:08.350821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bede3c340be9'
down_revision: Union[str, Sequence[str], None] = '03a6519ac6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.Enum('RS256', 'ES256', name='key_algorithm_enum'), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', name='key_status_enum'), nullable=False),
    sa.Column('activation_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signing_keys'))
    )
    op.create_index(op.f('ix_signing_keys_activation_date'), 'signing_keys', ['activation_date'], unique=False)
    op.create_index(op.f('ix_signing_keys_algorithm'), 'signing_keys', ['algorithm'], unique=False)
    op.create_index(op.f('ix_signing_keys_expiration_date'), 'signing_keys', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_signing_keys_id'), 'signing_keys', ['id'], unique=False)
    op.create_index(op.f('ix_signing_keys_key_id'), 'signing_keys', ['key_id'], unique=True)
    op.create_index(op.f('ix_signing_keys_status'), 'signing_keys', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signing_keys_status'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_key_id'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_id'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_expiration_date'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_algorithm'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_activation_date'), table_name='signing_keys')
    op.drop_table('signing_keys')
    # ### end Alembic commands ###
